# Generated by Django 5.2.3 on 2025-07-02 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 2, 12, 8, 7, 300937, tzinfo=datetime.timezone.utc)),
        ),
    ]
